# Generated by Django 3.2.14 on 2022-07-22 13:24

import appqmx.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JbxT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stj_JbkhM', models.CharField(default='福建省云启智创科技有限公司', max_length=32, verbose_name='开户名')),
                ('stj_JbkhH', models.CharField(max_length=32, verbose_name='开户行')),
                ('stj_JbyhzH', models.CharField(max_length=32, verbose_name='账号')),
                ('stj_JbjbnamE', models.CharField(max_length=32, verbose_name='经办人')),
                ('stj_JbjbPN', models.CharField(max_length=11, verbose_name='联系电话')),
                ('stj_JbbZ', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
                'db_table': 'JbxT',
            },
        ),
        migrations.CreateModel(
            name='KhlB',
            fields=[
                ('stk_KbiD', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='类别')),
                ('stk_KbxQ', models.CharField(max_length=32, verbose_name='详情')),
            ],
            options={
                'verbose_name': '客户类别表"',
                'verbose_name_plural': '客户类别表"',
                'db_table': 'KhlB',
            },
        ),
        migrations.CreateModel(
            name='YhxT',
            fields=[
                ('stu_UxtimE', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stu_UxnuM', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='账号')),
                ('stu_UxpwD', models.CharField(max_length=32, verbose_name='密码')),
                ('stu_UxnamE', models.CharField(max_length=32, verbose_name='姓名')),
                ('stu_UxmZ', models.CharField(max_length=32, verbose_name='民族')),
                ('stu_UxxB', models.CharField(choices=[('0', '男'), ('1', '女')], default='男', max_length=10, verbose_name='性别')),
                ('stu_Uxphone', models.CharField(max_length=11, unique=True, verbose_name='手机号码')),
                ('stu_UxzY', models.CharField(blank=True, max_length=32, verbose_name='专业')),
                ('stu_UxjG', models.CharField(blank=True, max_length=32, verbose_name='籍贯')),
                ('stu_UxsR', models.DateField(blank=True, max_length=32, verbose_name='生日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'YhxT',
            },
        ),
        migrations.CreateModel(
            name='KhxT',
            fields=[
                ('stk_KhiD', models.CharField(default=appqmx.models.khgetohtid, max_length=11, primary_key=True, serialize=False, verbose_name='客户编号')),
                ('stk_KhaecnamE', models.CharField(max_length=25, verbose_name='企业名称')),
                ('stk_KhjbnamE', models.CharField(max_length=32, verbose_name='经办人')),
                ('stk_KhjbdH', models.CharField(max_length=32, verbose_name='电话联系方式')),
                ('stk_KhdZ', models.CharField(max_length=32, verbose_name='企业地址')),
                ('stk_KhlxnamE', models.CharField(blank=True, max_length=32, verbose_name='联系人')),
                ('stk_KhlxdH', models.CharField(blank=True, max_length=32, verbose_name='电话联系方式')),
                ('stk_KhsydZ', models.CharField(blank=True, max_length=32, verbose_name='设备使用地址')),
                ('stk_KhlB', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D'), ('4', 'E'), ('5', 'F'), ('6', 'G')], max_length=32, verbose_name='客户类别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '客户信息表',
                'verbose_name_plural': '客户信息表',
                'db_table': 'KhxT',
            },
        ),
        migrations.CreateModel(
            name='jhxT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhb_pM', models.CharField(max_length=32, verbose_name='品名')),
                ('jhb_xH', models.CharField(max_length=32, verbose_name='型号')),
                ('jhb_JxiD', models.CharField(max_length=32, verbose_name='机号')),
                ('jhb_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '机号别表',
                'verbose_name_plural': '机号别表',
                'db_table': 'jhxT',
            },
        ),
        migrations.CreateModel(
            name='HtxT',
            fields=[
                ('sth_HtID', models.CharField(default=appqmx.models.htgetohtid, max_length=32, primary_key=True, serialize=False, verbose_name='合同编号')),
                ('sth_HtqssJ', models.DateField(auto_now_add=True, verbose_name='合同记录起始时间')),
                ('sth_HtjfnamE', models.CharField(default='福建省云启智创科技有限公司', max_length=32, verbose_name='甲方名称')),
                ('sth_HtfwdZ', models.CharField(max_length=32, verbose_name='服务地点')),
                ('sth_HtyJ', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='押金金额')),
                ('sth_HtjbfwF', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='基本费')),
                ('sth_HtbyC', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='包印彩')),
                ('sth_HtbyH', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='包印黑')),
                ('sth_HtczhjE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='超张黑金')),
                ('sth_HtczcjE', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='超张彩金')),
                ('sth_HtcblX', models.CharField(choices=[('0', '月'), ('1', '季')], default='月', max_length=10, verbose_name='抄表类型')),
                ('sth_HtqysJ', models.DateField(verbose_name='合同生效时间')),
                ('sth_HtjzsJ', models.DateField(verbose_name='合同到期时间')),
                ('sth_HtczzqS', models.CharField(blank=True, default=12, max_length=32, verbose_name='总期数')),
                ('HtzlsC', models.FileField(blank=True, upload_to='static/images/yyzz/', verbose_name='合同资料上传')),
                ('Ht_delete', models.BooleanField(default=False, verbose_name='可抄表')),
                ('sth_HtjH', models.ManyToManyField(to='appqmx.jhxT', verbose_name='机号')),
                ('sth_HtyfnamE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appqmx.khxt', verbose_name='客户名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '合同信息表',
                'verbose_name_plural': '合同信息表',
                'db_table': 'HtxT',
            },
        ),
        migrations.CreateModel(
            name='CbxT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stc_CbqC', models.CharField(max_length=10, verbose_name='抄表期次')),
                ('stc_CbaecnamE', models.CharField(max_length=32, verbose_name='抄表客户信息')),
                ('stc_CbsycbsJ', models.CharField(blank=True, max_length=32, verbose_name='上月抄表时间')),
                ('stc_CbbccbsJ', models.CharField(max_length=32, verbose_name='本月抄表时间')),
                ('stc_CbH', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='本月黑')),
                ('stc_CbC', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='本月彩')),
                ('stc_CbsH', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='上月黑')),
                ('stc_CbsC', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='上月彩')),
                ('stc_CbsjH', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='实际黑')),
                ('stc_CbsjC', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='实际彩')),
                ('stc_CbczhjE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='超张黑金额')),
                ('stc_CbczcjE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='超张彩金额')),
                ('stc_CbbyhJ', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='本机合计')),
                ('stc_CbxH', models.CharField(max_length=32, null=True, verbose_name='型号')),
                ('stc_CbjH', models.CharField(max_length=32, null=True, verbose_name='机号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '抄表系统',
                'verbose_name_plural': '抄表系统',
                'db_table': 'CbxT',
            },
        ),
    ]
