# Generated by Django 3.2.14 on 2022-07-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appqmx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbxt',
            name='stc_Htbh',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='合同编号'),
        ),
    ]
