# Generated by Django 3.2.14 on 2022-07-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appqmx', '0002_auto_20220710_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htxt',
            name='sth_HtczzqS',
            field=models.CharField(blank=True, default=12, max_length=32, verbose_name='总期数'),
        ),
    ]
