# Generated by Django 3.2.14 on 2022-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appqmx', '0002_cbxt_stc_htbh'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbxTProxy',
            fields=[
            ],
            options={
                'verbose_name': '未抄表数据',
                'verbose_name_plural': '未抄表数据',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('appqmx.cbxt',),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbC',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='本月彩'),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbH',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='本月黑'),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbbyhJ',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='本机合计'),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbczcjE',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='超张彩金额'),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbczhjE',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='超张黑金额'),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbsC',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='上月彩'),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbsH',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='上月黑'),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbsjC',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='实际彩'),
        ),
        migrations.AlterField(
            model_name='cbxt',
            name='stc_CbsjH',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='实际黑'),
        ),
    ]
